### ISSUE TITLE
二期啥时候完成那

### ISSUE THREAD

**Issue by topicgit** [hequan2017/seal#1]
二期啥时候完成那，很喜欢这个项目想跟着学习哈

**Comment by hequan2017** [comment]
会抽时间写，代码仅供参考。

**Comment by topicgit** [comment]
点击资产管理后再点击添加资产， 此时资产管理的二级会关闭，点击资产管理的话没反应？请问这个怎么解决？ 另外 k8s连接上pod之后的终端只有半屏，请问这个怎么调整应该？多谢

**Comment by hequan2017** [comment]
第一个问题， 是 js 调整 左边导航 没加载上，你可以看一下  页面 最下面 控制 左边导航的js.
第二个问题，调整 xterm.js的相关设置就可以。详情百度。

**Comment by hequan2017** [comment]
不要用 360浏览器  兼容模式。
